import assert from 'node:assert/strict';
import test from 'node:test';
import { createMeetingPlan, defaultSubjectFor, renderPlanSummary } from '../lib/plan.mjs';
import { MeetingPlanError } from '../lib/request.mjs';
import { ceilStartToHalfHour, nextHalfHourSlot } from '../lib/time-policy.mjs';

const NOW = new Date('2026-07-22T00:00:00+08:00');

function plan(overrides = {}) {
  return createMeetingPlan({
    subject: '课程讨论',
    start: '2026-08-01T14:10:00+08:00',
    end: '2026-08-01T15:05:00+08:00',
    timeZone: 'Asia/Shanghai',
    ...overrides,
  }, NOW);
}

test('开始时间向上对齐到整/半点，结束时间按时长取整', () => {
  const result = plan();
  assert.equal(result.startOriginal, '2026-08-01T14:10:00+08:00');
  assert.equal(result.start, '2026-08-01T14:30:00+08:00');
  assert.equal(result.effectiveEnd, '2026-08-01T15:30:00+08:00');
  assert.equal(result.meetings[0].durationMinutes, 60);
  assert.equal(result.startAdjusted, true);
});

test('开始时间已是整半点时保持不变', () => {
  const result = plan({ start: '2026-08-01T14:30:00+08:00' });
  assert.equal(result.start, '2026-08-01T14:30:00+08:00');
  assert.equal(result.startAdjusted, false);
});

test('超过六小时会连续拆分并增加标题序号', () => {
  const result = plan({ end: '2026-08-01T21:01:00+08:00' });
  assert.equal(result.meetings.length, 2);
  assert.deepEqual(result.meetings.map(({ subject, durationMinutes }) => ({ subject, durationMinutes })), [
    { subject: '课程讨论（1/2）', durationMinutes: 360 },
    { subject: '课程讨论（2/2）', durationMinutes: 60 },
  ]);
});

test('相同请求产生稳定指纹，不同请求产生新指纹', () => {
  assert.equal(plan().fingerprint, plan().fingerprint);
  assert.notEqual(plan().fingerprint, plan({ subject: '不同主题' }).fingerprint);
});

test('无主题时按开始日期星期几生成默认主题', () => {
  const result = plan({ subject: undefined });
  assert.equal(result.subject, '周六会议');
  assert.equal(result.subjectAutoGenerated, true);
  assert.equal(result.meetings[0].subject, '周六会议');
});

test('主题不足 3 个字符时回退为默认主题（服务端实测要求至少 3 字符）', () => {
  for (const subject of ['', '   ', '讨论', '会']) {
    const result = plan({ subject });
    assert.equal(result.subject, '周六会议');
    assert.equal(result.subjectAutoGenerated, true);
  }
});

test('3 个及以上字符的主题保持不变', () => {
  const result = plan({ subject: ' 每周组会 ' });
  assert.equal(result.subject, '每周组会');
  assert.equal(result.subjectAutoGenerated, false);
});

test('defaultSubjectFor 覆盖一周七天', () => {
  assert.equal(defaultSubjectFor(new Date('2026-08-03T12:00:00+08:00')), '周一会议');
  assert.equal(defaultSubjectFor(new Date('2026-08-04T12:00:00+08:00')), '周二会议');
  assert.equal(defaultSubjectFor(new Date('2026-08-05T12:00:00+08:00')), '周三会议');
  assert.equal(defaultSubjectFor(new Date('2026-08-06T12:00:00+08:00')), '周四会议');
  assert.equal(defaultSubjectFor(new Date('2026-08-07T12:00:00+08:00')), '周五会议');
  assert.equal(defaultSubjectFor(new Date('2026-08-01T12:00:00+08:00')), '周六会议');
  assert.equal(defaultSubjectFor(new Date('2026-08-02T12:00:00+08:00')), '周日会议');
});

test('durationMinutes 可替代结束时间', () => {
  const result = plan({ start: '2026-08-01T14:30:00+08:00', durationMinutes: '120' });
  assert.equal(result.end, '2026-08-01T16:30:00+08:00');
  assert.equal(result.effectiveEnd, '2026-08-01T16:30:00+08:00');
  assert.equal(result.meetings[0].durationMinutes, 120);
});

test('拒绝非法时长、过去的开始时间、非上海时区和反向时间', () => {
  assert.throws(() => plan({ durationMinutes: '0' }), MeetingPlanError);
  assert.throws(() => plan({ durationMinutes: '-30' }), MeetingPlanError);
  assert.throws(() => plan({ start: '2026-07-21T14:00:00+08:00' }), MeetingPlanError);
  assert.throws(() => createMeetingPlan({ subject: '课程讨论', start: '2026-08-01T14:00:00+00:00', end: '2026-08-01T15:00:00+00:00', timeZone: 'Asia/Shanghai' }, NOW), MeetingPlanError);
  assert.throws(() => plan({ end: '2026-08-01T14:00:00+08:00' }), MeetingPlanError);
});

test('刚刚过去的当前半点会被对齐到下一个半点而非拒绝', () => {
  const now = new Date('2026-08-01T16:47:00+08:00');
  const result = createMeetingPlan({
    subject: '测试会议',
    start: '2026-08-01T16:30:00+08:00',
    end: '2026-08-01T18:30:00+08:00',
    timeZone: 'Asia/Shanghai',
  }, now);
  assert.equal(result.start, '2026-08-01T17:00:00+08:00');
  assert.equal(result.effectiveEnd, '2026-08-01T18:30:00+08:00');
});

test('超过半小时的过去时间仍然拒绝，避免静默改写', () => {
  const now = new Date('2026-08-01T16:47:00+08:00');
  assert.throws(() => createMeetingPlan({
    subject: '测试会议',
    start: '2026-08-01T14:00:00+08:00',
    end: '2026-08-01T16:00:00+08:00',
    timeZone: 'Asia/Shanghai',
  }, now), MeetingPlanError);
});

test('摘要包含有效开始时间与自动调整提示', () => {
  const summary = renderPlanSummary(plan({ subject: undefined }));
  assert.match(summary, /原始时间：2026-08-01T14:10:00\+08:00/);
  assert.match(summary, /有效开始：2026-08-01T14:30:00\+08:00/);
  assert.match(summary, /主题已自动设为「周六会议」/);
  assert.match(summary, /开始时间已对齐到整\/半点/);
});

test('ceilStartToHalfHour 与 nextHalfHourSlot 的取整行为', () => {
  assert.equal(format(ceilStartToHalfHour(new Date('2026-08-01T16:47:00+08:00'))), '2026-08-01T17:00:00+08:00');
  assert.equal(format(ceilStartToHalfHour(new Date('2026-08-01T17:00:00+08:00'))), '2026-08-01T17:00:00+08:00');
  // 90 秒提交缓冲：整半点整/半点临界时跳到下一个半点，避免"必须严格未来"被拒。
  assert.equal(format(nextHalfHourSlot(new Date('2026-08-01T16:47:00+08:00'))), '2026-08-01T17:00:00+08:00');
  assert.equal(format(nextHalfHourSlot(new Date('2026-08-01T17:00:00+08:00'))), '2026-08-01T17:30:00+08:00');
  assert.equal(format(nextHalfHourSlot(new Date('2026-08-01T16:59:30+08:00'))), '2026-08-01T17:30:00+08:00');
});

function format(date) {
  return new Intl.DateTimeFormat('sv-SE', {
    timeZone: 'Asia/Shanghai',
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23',
  }).format(date).replace(' ', 'T') + '+08:00';
}
