import { fingerprintPlan, requestIdFromFingerprint } from './fingerprint.mjs';
import { normalizeMeetingOptions } from './options.mjs';
import { formatShanghai, parseRequest } from './request.mjs';
import { assertFutureStart, ceilEndToHalfHour, ceilStartToHalfHour, nextHalfHourSlot, splitIntoMeetings } from './time-policy.mjs';

const HALF_HOUR_MS = 30 * 60 * 1000;
const WEEKDAY_CHAR = { Mon: '一', Tue: '二', Wed: '三', Thu: '四', Fri: '五', Sat: '六', Sun: '日' };

export function defaultSubjectFor(date) {
  const weekday = new Intl.DateTimeFormat('en-US', { timeZone: 'Asia/Shanghai', weekday: 'short' }).format(date);
  return `周${WEEKDAY_CHAR[weekday] ?? ''}会议`;
}

export function createMeetingPlan(input, now = new Date()) {
  const request = parseRequest(input);
  const normalizedOptions = normalizeMeetingOptions(rawOptions(input));

  // 服务端要求主题至少 3 个字符；缺省或过短时使用默认主题「周X会议」。
  const subjectAutoGenerated = request.subject.length < 3;
  const subject = subjectAutoGenerated ? defaultSubjectFor(request.start) : request.subject;

  // 服务端仅接受整点/半点开始，且必须严格在未来：向上对齐可同时满足两者。
  // 对齐后仍在过去、但距现在不超过半小时（正在进行中的时段）时，视为"马上开会"，取下一个半点；
  // 更久远的过去时间保持报错，避免静默改写用户指定的时间。
  let alignedStart = ceilStartToHalfHour(request.start);
  if (alignedStart.getTime() <= now.getTime()) {
    if (now.getTime() - request.start.getTime() <= HALF_HOUR_MS) {
      alignedStart = nextHalfHourSlot(now);
    } else {
      assertFutureStart(alignedStart, now);
    }
  }
  const startAdjusted = alignedStart.getTime() !== request.start.getTime();

  const effectiveEnd = ceilEndToHalfHour(alignedStart, request.end);
  const meetings = splitIntoMeetings(subject, alignedStart, effectiveEnd).map((meeting) => ({
    ...meeting,
    start: formatShanghai(meeting.start),
    end: formatShanghai(meeting.end),
  }));
  const canonical = {
    schemaVersion: 2,
    subject,
    start: formatShanghai(alignedStart),
    startOriginal: formatShanghai(request.start),
    startAdjusted,
    subjectAutoGenerated,
    end: formatShanghai(request.end),
    effectiveEnd: formatShanghai(effectiveEnd),
    timeZone: request.timeZone,
    options: {
      payloadOverrides: normalizedOptions.payloadOverrides,
      notes: normalizedOptions.notes,
    },
    meetings,
  };
  const fingerprint = fingerprintPlan(canonical);

  return {
    ...canonical,
    status: 'ready_for_confirmation',
    requestId: requestIdFromFingerprint(fingerprint),
    fingerprint: `sha256:${fingerprint}`,
    shortFingerprint: fingerprint.slice(0, 12),
    confirmation: {
      required: true,
      acceptedValues: [requestIdFromFingerprint(fingerprint), fingerprint.slice(0, 12)],
    },
    calendar: { policy: 'after_approval_only' },
  };
}

export function renderPlanSummary(plan) {
  const rows = plan.meetings.map((meeting) => (
    `  ${meeting.sequence}. ${meeting.subject}\n     ${meeting.start} → ${meeting.end}（${meeting.durationMinutes} 分钟）`
  ));

  const optionLines = plan.options?.notes?.length ? [`已启用自定义选项：`, ...plan.options.notes.map((note) => `  · ${note}`)] : [];

  const notes = [];
  if (plan.subjectAutoGenerated) {
    notes.push(`主题已自动设为「${plan.subject}」（服务端要求主题至少 3 个字符）。`);
  }
  if (plan.startAdjusted) {
    notes.push(`开始时间已对齐到整/半点：${plan.startOriginal} → ${plan.start}（服务端仅接受整点/半点开始，且必须在未来）。`);
  }

  return [
    `请求 ID：${plan.requestId}`,
    `原始时间：${plan.startOriginal} → ${plan.end}`,
    `有效开始：${plan.start}`,
    `有效结束时间：${plan.effectiveEnd}`,
    ...notes.map((note) => `提示：${note}`),
    ...optionLines,
    '以下申请提交后均须等待管理员审批：',
    ...rows,
  ].join('\n');
}

function rawOptions(input) {
  const raw = input?.options;
  if (!raw || typeof raw !== 'object') return {};
  return {
    ...raw,
    fields: typeof raw.fields === 'string' ? [raw.fields] : raw.fields,
  };
}
